/**
 * Generates app/assets/css/tokens.css from tokens.json (W3C DTCG format).
 * Run: npm run tokens:build
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = fileURLToPath(new URL('..', import.meta.url))
const tokens = JSON.parse(readFileSync(new URL('../tokens.json', import.meta.url), 'utf8'))

/** @returns {Array<[string, string]>} [cssVariable, value] pairs, aliases resolved */
function flatten(group, path = []) {
  return Object.entries(group).flatMap(([key, node]) => {
    if (key.startsWith('$')) return []
    if (typeof node.$value === 'string') {
      const alias = /^\{(.+)\}$/.exec(node.$value)
      const value = alias ? resolve(alias[1].split('.')) : node.$value
      return [[`--${[...path, key].join('-').replaceAll('_', '-')}`, value]]
    }
    return flatten(node, [...path, key])
  })
}

/** @param {string[]} path */
function resolve(path) {
  const node = path.reduce((acc, key) => acc?.[key], tokens)
  if (typeof node?.$value !== 'string' || node.$value.startsWith('{')) {
    throw new Error(`Unresolvable token alias: {${path.join('.')}}`)
  }
  return node.$value
}

const variables = flatten(tokens)
  .map(([name, value]) => `  ${name}: ${value};`)
  .join('\n')

const css = `/* Generated by scripts/build-tokens.mjs from tokens.json. Do not edit by hand. */\n:root {\n${variables}\n}\n`
const out = new URL('../app/assets/css/tokens.css', import.meta.url)
writeFileSync(out, css)
console.log(`tokens.css: ${variables.split('\n').length} variables written (from ${root})`)
